version: '3'
services:
  postgres:
    image: postgres
    # image: kartoza/postgis:9.6-2.4 
    # image: kartoza/postgis:9.6-2.4
    # image: postgres:9.6.11-alpine    
    
    hostname: postgres
    # container_name: postgres

    ports:
      # - "6543:5432"
      - "5432:5432"      
    environment:
      # POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: postgres
      # POSTGRES_DBNAME: db_amex01     
      # POSTGRES_DB: TEST_SM

      POSTGRES_USER: postgres
      POSTGRES_DBNAME: db_amex01
      POSTGRES_PASS: postgres
    volumes:
      # - postgres-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d/

    restart: unless-stopped

  pgadmin:
    # https://hub.docker.com/r/dpage/pgadmin4/
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped



  todo:
    build: ./go_amex/
    depends_on:
      - "postgres"
    restart: always

    ports:
      # - "8000:8080"
      - "8000:8000"



volumes:
  postgres-data:
